### ISSUE TITLE
Request: add CHANGE file

### ISSUE THREAD

**Issue by st-clair-clarke** [zuriscript/signalstory#25]
Hi fellows.
I am enjoying using the library. It is quite simple to use and yet provides most of the tools for state management.
However, when new releases are made, I don't know what the changes are. Could we get a summary of changes made to the library so we could use changes.

**Comment by zuriscript** [comment]
I am using  [github relase](https://github.com/zuriscript/signalstory/releases) for indicating a new release and npm publish.
There you can see all breaking changes and new feature, directly linked with the PR.
Would you see any benefits of maintaining a separate CHANGELOG file at this early stage?

**Comment by st-clair-clarke** [comment]
The content at github release is enough. Thanks. The CHANGELOG is not necessary at the moment.

**Comment by zuriscript** [comment]
Perfect, I will soon fix some conventions for PR and contribution stuff, hence the release notes should be more unified in the future.
